# Generated by Django 3.2.9 on 2022-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='colour',
            field=models.CharField(choices=[('Azure', 'Default'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Salmon', 'Salmon'), ('Aqua', 'Cyan'), ('Chartreuse', 'Lime Green'), ('Gray', 'Gray')], default='White', max_length=20),
        ),
    ]
